package de.webis.hadoop.counter;

public enum ImageFilterCounter {
    REFERENCE_COUNT_IMAGES,
    REFERENCE_COUNT_REFERENCES,
    NON_PARSABLE_IMAGES,
    NON_PARSABLE_REFERENCES,
    NON_EXISTENT_IMAGES,
    NON_EXISTENT_REFERENCES,
    IMAGE_SIZE_IMAGES,
    IMAGE_SIZE_REFERENCES
}
