package de.webis.hadoop.counter;

public enum PipelineCounter {
    INPUT_IMAGE_FILTER_REFERENCES,
    INPUT_IMAGE_FILTER_UNIQUE_IMAGES,
    INPUT_IMAGE_FILTER_CAPTIONS,

    INPUT_CAPTION_FILTER_REFERENCES,
    INPUT_CAPTION_FILTER_UNIQUE_IMAGES,
    INPUT_CAPTION_FILTER_CAPTIONS,

    INPUT_IMAGE_MATCHER_REFERENCES,
    INPUT_IMAGE_MATCHER_CAPTIONS,

    INPUT_PARAPHRASE_CONSTRUCTION_DISTINCT_URLS,
    INPUT_PARAPHRASE_CONSTRUCTION_REFERENCES,

    INPUT_PARAPHRASE_FILTER,
}
