package de.webis.hadoop.counter;

public enum TableCounter {
    A_IMAGES_NO_FILTER,
    A_REFERENCES_NO_FILTER,
    A_REFERENCES_GEQ_2,
    A_REFERENCES_GEQ_5,
    A_CAPTIONS_NO_FILTER,
    A_PARAPHRASE_PAIRS_NO_FILTER,

    B_REFERENCES_NUM_REFERENCES,
    B_CAPTIONS_NUM_REFERENCES,

    C_REFERENCES_HAVE_CAPTIONS,
    C_CAPTIONS_HAVE_CAPTIONS,

    D_CAPTIONS_NON_EMPTY,
    E_CAPTIONS_LONG_ENOUGH,
    F_CAPTIONS_SENTENCES,
    F_CAPTIONS_VERBS,

    G_REFERENCES_HAVE_CAPTIONS_PASSING,
    G_CAPTIONS_HAVE_CAPTIONS_PASSING,
}
