package de.webis.hadoop.counter;

public enum WikiImageExtractionCounter {
    ARTICLES_WITH_INFOBOXES,

    REFERENCES_IN_BODY,
    REFERENCES_IN_TEMPLATES,
    REFERENCES_IN_INFOBOXES,

    INFOBOXES_WITH_REFERENCES,
    INFOBOXES_WITH_REFERENCES_AND_CAPTIONS
}
